#server
server:
  port: 8099
  servlet:
    context-path: /
#spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/medicine?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false
mybatis:
  type-aliases-package: com.cy.pojo
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true

    
    
    
    
    
    
    
    
    
    
    